modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "${mod_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
modId = "forge"
type = "required"
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "octolib"
type="required"
versionRange = "[0.4.2,)"
ordering = "NONE"
side = "BOTH"