modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
modId = "nerb"
version = "${file.jarVersion}"
displayName = "NotEnoughRecipeBook"
authors = "SSKirillSS"
description = '''

'''
[[dependencies.nerb]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nerb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
