modLoader = "javafml"
loaderVersion = "[35,)"
license = "All Rights Reserved"
[[mods]]
modId = "nerb"
version = "${file.jarVersion}"
displayName = "NotEnoughRecipeBook"
authors = "SSKirillSS"
description = '''

'''
[[dependencies.nerb]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"