modLoader = "javafml"
loaderVersion = "[45,)"
license = "All Rights Reserved"
[[mods]]
modId = "nerb"
version = "${file.jarVersion}"
displayName = "NotEnoughRecipeBook"
authors = "SSKirillSS"
description = '''

'''
[[dependencies.nerb]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nerb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
