modLoader = "javafml"
loaderVersion = "[35,)"
license = "All Rights Reserved"
[[mods]]
modId = "nerb"
version = "${file.jarVersion}"
displayName = "NotEnoughRecipeBook"
authors = "SSKirillSS"
description = '''

'''
[[dependencies.nerb]]
modId = "forge"
mandatory = true
versionRange = "[40.1.68,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nerb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1-5.0.4.2,)"
ordering = "NONE"
side = "BOTH"
