modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"

[[mixins]]
config = "${mod_id}-common.mixins.json"
[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"